# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    jenkins.vm.network "private_network", ip: "172.28.128.14" 
	#type: "dhcp" 
	#ip: "192.168.50.45"
	#virtualbox__intnet: true
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "jenkins"
      v.memory = 2048
      v.cpus = 2
	  #v__intnet = true
	  #config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
    end
    jenkins.vm.provision :shell do |shell|
      shell.path = "install_jenkins.sh"
    end
  end
end