# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
RAM = 1024
CPU = 1
Vagrant.configure("2") do |config|
  # configuration VM1 Lod Balancer
  config.vm.define "lb" do |lb|
    lb.vm.box = "geerlingguy/centos7"
    lb.vm.provider "virtualbox" do |v|
      v.memory = RAM 
      v.cpus = CPU 
    end
    lb.vm.network "private_network", ip: "10.0.0.10"
	lb.vm.hostname = "lb" # cette fonction hostname a été rendu disponible grace au plugin "vagrant-hostsupdater" que nous avons ajouté en l'installant dans notre vagrant
  end
  
  # configuration VM2 web1
  config.vm.define "web1" do |web1|
    web1.vm.box = "geerlingguy/centos7"
    web1.vm.provider "virtualbox" do |v|
      v.memory = RAM 
      v.cpus = CPU 
    end
    web1.vm.network "private_network", ip: "10.0.0.11"
	web1.vm.hostname = "web1"
  end
  
  # configuration VM2 web2
  config.vm.define "web2" do |web2|
    web2.vm.box = "geerlingguy/centos7"
    web2.vm.provider "virtualbox" do |v|
      v.memory = RAM 
      v.cpus = CPU 
    end
    web2.vm.network "private_network", ip: "10.0.0.12"
	web2.vm.hostname = "web2"
  end
  
end
